DROP  TABLE IF EXISTS POSTS;
DROP TABLE IF EXISTS COMMENTS;

CREATE TABLE POSTS (
    ID INT NOT NULL AUTO_INCREMENT,
    TITLE VARCHAR(50) NOT NULL ,
    DESCRIPTION VARCHAR(500) NOT NULL ,
    BODY LONGTEXT DEFAULT NULL,
     POST_STATUS ENUM("DRAFT", "PUBLISHED"),
    CREATED_ON DATETIME NOT NULL,
    UPDATED_ON DATETIME NOT NULL ,
    PRIMARY KEY(ID)

);